<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260719173837 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Core domain schema (album, photo, location, tag, person, face, admin_user) and pgvector extension';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE EXTENSION IF NOT EXISTS vector');
        $this->addSql('CREATE TABLE admin_user (id UUID NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AD8A54A9E7927C74 ON admin_user (email)');
        $this->addSql('CREATE TABLE album (id UUID NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(255) NOT NULL, visibility VARCHAR(20) NOT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, parent_id UUID DEFAULT NULL, cover_photo_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_39986E43989D9B62 ON album (slug)');
        $this->addSql('CREATE INDEX IDX_39986E43727ACA70 ON album (parent_id)');
        $this->addSql('CREATE INDEX IDX_39986E43A69B8AD7 ON album (cover_photo_id)');
        $this->addSql('CREATE TABLE face (id UUID NOT NULL, x DOUBLE PRECISION DEFAULT NULL, y DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, crop_path VARCHAR(1024) DEFAULT NULL, confidence DOUBLE PRECISION DEFAULT NULL, embedding vector(512) DEFAULT NULL, has_embedding BOOLEAN NOT NULL, photo_id UUID NOT NULL, person_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5147B677E9E4C8C ON face (photo_id)');
        $this->addSql('CREATE INDEX IDX_5147B67217BBB47 ON face (person_id)');
        $this->addSql('CREATE TABLE location (id UUID NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, latitude DOUBLE PRECISION DEFAULT NULL, longitude DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE person (id UUID NOT NULL, name VARCHAR(255) DEFAULT NULL, is_named BOOLEAN NOT NULL, avatar_face_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_34DCD1762BA6630E ON person (avatar_face_id)');
        $this->addSql('CREATE TABLE photo (id UUID NOT NULL, title VARCHAR(255) DEFAULT NULL, taken_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, width INT DEFAULT NULL, height INT DEFAULT NULL, original_path VARCHAR(1024) NOT NULL, avif_path VARCHAR(1024) DEFAULT NULL, thumb_paths JSON NOT NULL, processing_status VARCHAR(20) NOT NULL, processing_error TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, album_id UUID NOT NULL, location_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_14B784181137ABCF ON photo (album_id)');
        $this->addSql('CREATE INDEX IDX_14B7841864D218E ON photo (location_id)');
        $this->addSql('CREATE TABLE photo_tag (photo_id UUID NOT NULL, tag_id UUID NOT NULL, PRIMARY KEY (photo_id, tag_id))');
        $this->addSql('CREATE INDEX IDX_8C2D8E577E9E4C8C ON photo_tag (photo_id)');
        $this->addSql('CREATE INDEX IDX_8C2D8E57BAD26311 ON photo_tag (tag_id)');
        $this->addSql('CREATE TABLE tag (id UUID NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_389B783989D9B62 ON tag (slug)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE album ADD CONSTRAINT FK_39986E43727ACA70 FOREIGN KEY (parent_id) REFERENCES album (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE album ADD CONSTRAINT FK_39986E43A69B8AD7 FOREIGN KEY (cover_photo_id) REFERENCES photo (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE face ADD CONSTRAINT FK_5147B677E9E4C8C FOREIGN KEY (photo_id) REFERENCES photo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE face ADD CONSTRAINT FK_5147B67217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1762BA6630E FOREIGN KEY (avatar_face_id) REFERENCES face (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B784181137ABCF FOREIGN KEY (album_id) REFERENCES album (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo ADD CONSTRAINT FK_14B7841864D218E FOREIGN KEY (location_id) REFERENCES location (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE photo_tag ADD CONSTRAINT FK_8C2D8E577E9E4C8C FOREIGN KEY (photo_id) REFERENCES photo (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE photo_tag ADD CONSTRAINT FK_8C2D8E57BAD26311 FOREIGN KEY (tag_id) REFERENCES tag (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE album DROP CONSTRAINT FK_39986E43727ACA70');
        $this->addSql('ALTER TABLE album DROP CONSTRAINT FK_39986E43A69B8AD7');
        $this->addSql('ALTER TABLE face DROP CONSTRAINT FK_5147B677E9E4C8C');
        $this->addSql('ALTER TABLE face DROP CONSTRAINT FK_5147B67217BBB47');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD1762BA6630E');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B784181137ABCF');
        $this->addSql('ALTER TABLE photo DROP CONSTRAINT FK_14B7841864D218E');
        $this->addSql('ALTER TABLE photo_tag DROP CONSTRAINT FK_8C2D8E577E9E4C8C');
        $this->addSql('ALTER TABLE photo_tag DROP CONSTRAINT FK_8C2D8E57BAD26311');
        $this->addSql('DROP TABLE admin_user');
        $this->addSql('DROP TABLE album');
        $this->addSql('DROP TABLE face');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE photo');
        $this->addSql('DROP TABLE photo_tag');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
